networks:
  proxy_net:
    name: proxy_net
    # internal: true # does not work with nextcloud
    driver: bridge
    ipam:
      config:
        - subnet: ${PROXY_NET_SUBNET}
          gateway: ${PROXY_NET_GATEWAY}
  # frontend_net:
  #   name: frontend_net
  #   driver: bridge

services:
  reverse_proxy:
    container_name: reverse_proxy
    networks:
      - proxy_net
      # - frontend_net
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/error.log:/var/log/nginx/error.log
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    # only needed for templates
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped

include:
  - ./pihole/docker-compose.yml
  - ./kosync/docker-compose.yml
  - ./nc-compose.yml
  - ./jellyfin/docker-compose.yml
  - ./certbot/docker-compose.yml
