server {
    listen 443 ssl;
    # listen [::]:443 ssl; # Listen on IPv6 port 80

    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

    server_name wallabag.mydomain.com;

	location / {
		proxy_pass http://wallabag:80;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
	}
}
