server {
    listen 443 ssl;

    client_max_body_size 16M;

    # set headers
    proxy_set_header host              $host;

    # proxy_set_header Connection        $http_connection;
    proxy_set_header x-real-ip         $remote_addr;
    proxy_set_header x-forwarded-for   $proxy_add_x_forwarded_for;
    proxy_set_header x-forwarded-proto $scheme;

    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

    server_name miniflux.mydomain.com;

    location / {
        proxy_pass http://miniflux:8080;
    }
}
